-- Oracle feature sample for Irodori Table.
-- Run against `make db-up DB=oracle`.

select sys_context('USERENV', 'SERVICE_NAME') as service_name from dual;

begin
  execute immediate 'drop table irodori_oracle_orders purge';
exception
  when others then
    if sqlcode != -942 then
      raise;
    end if;
end;
/

create table irodori_oracle_orders (
  id number generated by default as identity primary key,
  customer_name varchar2(200) not null,
  total number(12,2) not null,
  created_at timestamp default systimestamp not null,
  attrs clob check (attrs is json)
);

insert into irodori_oracle_orders (customer_name, total, attrs)
values ('Kawase Foods', 98412.00, json_object('tier' value 'gold'));

insert into irodori_oracle_orders (customer_name, total, attrs)
values ('Northwind Retail', 77201.00, json_object('tier' value 'silver'));

select id,
       customer_name,
       json_value(attrs, '$.tier') as tier,
       total,
       dense_rank() over (order by total desc) as revenue_rank
from irodori_oracle_orders
order by id
fetch first 10 rows only;

explain plan for
select customer_name, total
from irodori_oracle_orders
where total > 80000;

select * from table(dbms_xplan.display);
