#!/usr/bin/env node
// Render a human-readable summary of one knowledge refresh run.
//
// Inputs: the --report-json file written by refresh.mjs (per-source outcomes)
// plus the knowledge DB (for facts recorded since the run started). Output is
// a Markdown report used as the scheduled PR body and committed to
// registry/knowledge-refresh-report.md for mirroring into irodori-docs.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";

await main(process.argv.slice(2));

async function main(argv) {
  const args = parseArgs(argv);
  if (!args.results || args.help) {
    console.error(
      "usage: node tools/knowledge/refresh-report.mjs --results <refresh-results.json>" +
        " [--db <path>] [--out <path>]"
    );
    process.exit(args.help ? 0 : 1);
  }

  const root = resolve(new URL("../..", import.meta.url).pathname);
  const dbPath = resolve(root, args.db ?? "knowledge/irodori-knowledge.sqlite");
  const outPath = resolve(root, args.out ?? "registry/knowledge-refresh-report.md");
  const run = JSON.parse(readFileSync(resolve(args.results), "utf8"));

  const results = [...(run.results ?? [])].sort((a, b) => a.id.localeCompare(b.id));
  const stored = results.filter((entry) => entry.outcome === "stored");
  const unchanged = results.filter((entry) => entry.outcome === "unchanged");
  const failed = results.filter((entry) => entry.outcome === "failed");

  const db = new DatabaseSync(dbPath);
  const newFacts = db
    .prepare(`
      select product, count(*) as count
      from facts
      where datetime(observed_at) >= datetime(?)
      group by product
      order by count desc, product asc
    `)
    .all(run.startedAt);
  const totalNewFacts = newFacts.reduce((sum, row) => sum + row.count, 0);

  const lines = [];
  lines.push("# Knowledge Refresh Report");
  lines.push("");
  lines.push(`Run started ${run.startedAt}, finished ${run.finishedAt} (UTC).`);
  lines.push("");
  lines.push("| Metric | Count |");
  lines.push("| --- | ---: |");
  lines.push(`| Sources checked | ${results.length} |`);
  lines.push(`| Changed (new snapshot) | ${stored.length} |`);
  lines.push(`| Unchanged | ${unchanged.length} |`);
  lines.push(`| Failed | ${failed.length} |`);
  lines.push(`| New facts | ${totalNewFacts} |`);

  lines.push("");
  lines.push(`## Changed sources (${stored.length})`);
  lines.push("");
  if (stored.length === 0) {
    lines.push("None — no upstream changes detected.");
  } else {
    lines.push("| Source | Product | Latest title |");
    lines.push("| --- | --- | --- |");
    for (const entry of stored) {
      lines.push(`| ${cell(entry.id)} | ${cell(entry.product)} | ${cell(entry.title ?? "")} |`);
    }
  }

  lines.push("");
  lines.push(`## Failed sources (${failed.length})`);
  lines.push("");
  if (failed.length === 0) {
    lines.push("None.");
  } else {
    lines.push("| Source | Product | Error |");
    lines.push("| --- | --- | --- |");
    for (const entry of failed) {
      lines.push(`| ${cell(entry.id)} | ${cell(entry.product)} | ${cell(entry.error ?? "")} |`);
    }
  }

  lines.push("");
  lines.push(`## New facts by product (${totalNewFacts})`);
  lines.push("");
  if (newFacts.length === 0) {
    lines.push("None recorded during this run.");
  } else {
    lines.push("| Product | New facts |");
    lines.push("| --- | ---: |");
    for (const row of newFacts) {
      lines.push(`| ${cell(row.product)} | ${row.count} |`);
    }
  }

  lines.push("");
  lines.push(
    "_Generated by `tools/knowledge/refresh-report.mjs` from the scheduled knowledge" +
      " refresh. The knowledge SQLite DB itself is gitignored; this report and the" +
      " regenerated cheatsheets are the reviewable output. Mirrored to the public" +
      " docs site (`irodori-docs`)._"
  );
  lines.push("");

  writeFileSync(outPath, lines.join("\n"));
  console.log(`refresh-report: ${outPath}`);
  console.log(
    `checked ${results.length}, stored ${stored.length}, unchanged ${unchanged.length},` +
      ` failed ${failed.length}, new facts ${totalNewFacts}`
  );
}

function cell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ").slice(0, 160);
}

function parseArgs(values) {
  const parsed = {};
  for (let index = 0; index < values.length; index += 1) {
    const value = values[index];
    if (!value.startsWith("--")) continue;
    const key = value.slice(2);
    const next = values[index + 1];
    if (!next || next.startsWith("--")) {
      parsed[key] = true;
    } else {
      parsed[key] = next;
      index += 1;
    }
  }
  return parsed;
}
