-- Irodori sample schema (PostgreSQL). Loaded on first container init.
-- Small, hand-checked demo data. Bulk/scale data is generated by scripts/dev-db.sh seed.

create table customers (
  id         integer primary key,
  name       text not null,
  created_at timestamptz not null default now()
);

create table orders (
  id          integer primary key,
  customer_id integer not null references customers(id),
  total       numeric(12,2) not null,
  created_at  timestamptz not null default now()
);

create table invoice_lines (
  id       integer primary key,
  order_id integer not null references orders(id),
  sku      text not null,
  qty      integer not null,
  amount   numeric(12,2) not null
);

insert into customers (id, name) values
  (1, 'Kawase Foods'),
  (2, 'Northwind Retail'),
  (3, 'Aster Works'),
  (4, 'Minato Labs');

insert into orders (id, customer_id, total, created_at) values
  (101, 1, 98412.00, now() - interval '1 day'),
  (102, 2, 77201.00, now() - interval '2 days'),
  (103, 1, 65330.00, now() - interval '3 days'),
  (104, 3, 51288.00, now() - interval '4 days');

insert into invoice_lines (id, order_id, sku, qty, amount) values
  (1, 101, 'SKU-001', 3, 32804.00),
  (2, 101, 'SKU-002', 1, 65608.00),
  (3, 102, 'SKU-003', 2, 77201.00),
  (4, 103, 'SKU-001', 5, 65330.00),
  (5, 104, 'SKU-004', 4, 51288.00);

create view recent_revenue as
  select c.id as customer_id,
         c.name,
         sum(o.total)      as lifetime_value,
         max(o.created_at) as last_order_at
  from customers c
  join orders o on o.customer_id = c.id
  group by c.id, c.name;
